/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.*;
import java.text.*;
import java.util.*;
import java.io.*;
import javax.swing.JOptionPane;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.*;

/**
 * /**
 *
 * @author Faiz
 */
public class Homepage extends javax.swing.JFrame { //gui homepage

    String username;

    Booking book = new Booking();
    BookingCheck bookingcheck = new BookingCheck();
    private Statement st;
    PreparedStatement pst;
    private ResultSet rs;
    Connection con = null;

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    public Homepage(String username) {
        initComponents();
        this.username = username;
        usernamefield.setText(username);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jToggleButton1 = new javax.swing.JToggleButton();
        textArea1 = new java.awt.TextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        usernamefield = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        sss = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jToggleButton1.setText("jToggleButton1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        jLabel3.setText("Your username");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 20, 200, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Change Info");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(540, 30, 110, 30);

        usernamefield.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        usernamefield.setText("jLabel2");
        jPanel1.add(usernamefield);
        usernamefield.setBounds(40, 60, 83, 22);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Log Out");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(691, 30, 90, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/deluxe executive.jpg"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 690, 200, 140);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("DELUXE KING ROOM");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(360, 120, 200, 20);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("SUITE ROOM");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(360, 310, 130, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("DELUXE QUEEN ROOM");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(360, 490, 210, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("PREMIER SINGLE ROOM");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(360, 680, 230, 20);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(3);
        jTextArea1.setRows(5);
        jTextArea1.setText("Live and rest like a royalty with our Single Room. \nIt has a total floor size of 258 ft²\nand is equipped with upscale furnishings\nto make sure guests would enjoy a relaxing and serene stay in our hotel.\n\n✅Air conditioned\n✅Bath\n✅Bathrobes Provided\n✅Daily Room Service\n✅Fridge - Bar Fridge\n✅Hairdryer\n✅Iron/Ironing board\n✅King Bed\n✅Linen and Towels Provided\n✅Linen Provided\n✅Mini Bar\n✅Mini Fridge\n✅Tea/Coffee Making\n✅Telephone\n✅Television\n✅Wireless Internet"); // NOI18N
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(360, 700, 420, 120);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(3);
        jTextArea2.setRows(5);
        jTextArea2.setText("With a total floor size of 323 ft², \nour Deluxe King Room features  \na king-size bed which could accommodate up to  \n2 adults and 2 kids aging 12 years old and below\n\n✅Air conditioned\n✅Bath\n✅Bathrobes Provided\n✅Daily Room Service\n✅Fridge - Bar Fridge\n✅Hairdryer\n✅Iron/Ironing board\n✅King Bed\n✅Linen and Towels Provided\n✅Linen Provided\n✅Mini Bar\n✅Mini Fridge\n✅Tea/Coffee Making\n✅Telephone\n✅Television\n✅Wireless Internet"); // NOI18N
        jScrollPane2.setViewportView(jTextArea2);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(360, 150, 420, 120);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("BOOK NOW");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(370, 280, 120, 25);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("BOOK NOW");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(370, 830, 120, 25);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(3);
        jTextArea3.setRows(5);
        jTextArea3.setText("The room has a total floor size of no less than 538 ft².\nUnlike the two Deluxe accommodations, \nthe Suite Room provides magnificent city view which is especially stunning at night. \nIt also has an added sofa set to give guests' the ultimate comfort they need after a long busy day.\n\n✅Air conditioned\n✅Bath\n✅Bathrobes Provided\n✅Daily Room Service\n✅Fridge - Bar Fridge\n✅Hairdryer\n✅Iron/Ironing board\n✅King Bed\n✅Linen and Towels Provided\n✅Linen Provided\n✅Mini Bar\n✅Mini Fridge\n✅Tea/Coffee Making\n✅Telephone\n✅Television\n✅Wireless Internet\n✅Room Safe"); // NOI18N
        jScrollPane3.setViewportView(jTextArea3);

        jPanel1.add(jScrollPane3);
        jScrollPane3.setBounds(360, 330, 420, 120);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(3);
        jTextArea4.setRows(5);
        jTextArea4.setText("This room has a total floor size of 323 ft². \nIt includes two queen-size \nwhich and has a maximum capacity of 2 adults and 2 kids \naging 12 years old and below.\n\n✅Air conditioned\n✅Bath\n✅Bathrobes Provided\n✅Daily Room Service\n✅Fridge - Bar Fridge\n✅Hairdryer\n✅Iron/Ironing board\n✅King Bed\n✅Linen and Towels Provided\n✅Linen Provided\n✅Mini Bar\n✅Mini Fridge\n✅Tea/Coffee Making\n✅Telephone\n✅Television\n✅Wireless Internet"); // NOI18N
        jScrollPane4.setViewportView(jTextArea4);

        jPanel1.add(jScrollPane4);
        jScrollPane4.setBounds(360, 520, 420, 120);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("BOOK NOW");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(380, 460, 120, 25);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("BOOK NOW");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(370, 650, 120, 25);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/deluxe executive.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 320, 200, 150);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/deluxe executive.jpg"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(90, 140, 200, 140);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/deluxe executive.jpg"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(90, 500, 200, 140);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("CHECK VACANCY");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(500, 280, 160, 25);

        jButton9.setBackground(new java.awt.Color(255, 255, 255));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setText("CHECK VACANCY");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(500, 650, 160, 25);

        jButton11.setBackground(new java.awt.Color(255, 255, 255));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setText("CHECK VACANCY");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(510, 460, 160, 25);

        jButton12.setBackground(new java.awt.Color(0, 0, 0));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("CHECK VACANCY");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(500, 650, 160, 25);

        jButton13.setBackground(new java.awt.Color(255, 255, 255));
        jButton13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton13.setText("CHECK VACANCY");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(510, 830, 160, 25);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setText("View All Room Status");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(330, 30, 180, 30);

        sss.setBackground(new java.awt.Color(255, 255, 255));
        sss.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sss.setText("Delete All booking");
        sss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sssActionPerformed(evt);
            }
        });
        jPanel1.add(sss);
        sss.setBounds(330, 70, 180, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(695, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(105, 105, 105))
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        setSize(new java.awt.Dimension(800, 869));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here: 
        fetch get = new fetch();

        ResultSet rs = null;
        String temppassword;
        String tempid;
        String tempusername;
        String tempic;
        String tempphone;
        String email;
        String tempname;
        rs = get.find(usernamefield.getText());

        ////problem dalam try
        try {

            if (rs.next()) {
                temppassword = rs.getString("Password");
                tempname = rs.getString("Name");
                tempid = rs.getString("userid");
                email = rs.getString("email");
                tempic = rs.getString("ICnumber");
                tempphone = rs.getString("Phonenumber");
                new Updateinfo(username, tempname, temppassword, tempid, tempic, tempphone, email).setVisible(true);
                this.dispose();
            } else {
                System.out.println("Error ");
            }

        } catch (Exception ex) {

        }

        /* System.out.println(username);
        try{
            
             String query = "SELECT * FROM `profile` WHERE `username` =?";
            pst=con.prepareStatement(query)
            String tempname;
            System.out.println(username);
          
            while(rs.next()){
                tempname=rs.getString("Name");
                System.out.println(tempname);
                if(username==tempname){
                 
                //String temppassword=rs.getString("Password");
                //String tempid=rs.getString("userid");
                //String tempusername=rs.getString("username");
               // String tempic=rs.getString("ICnumber");
                //String tempphone=rs.getString("Phonenumber");
                //new Updateinfo(tempusername,tempname,temppassword,tempid,tempic,tempphone).setVisible(true);
                }
                

                
            }
        }catch(Exception ex){
            System.out.println(ex);
        
        
        
        
        
        }  */
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "Logout Sucessfull");
        Loginform ab = new Loginform();
        ab.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        Roomchecker aa = new Roomchecker();
        aa.setVisible(true);


    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        Roomchecker aa = new Roomchecker();
        aa.setVisible(true);
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        Roomchecker aa = new Roomchecker();
        aa.setVisible(true);

    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Logout Sucessfull");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        Roomchecker aa = new Roomchecker();
        aa.setVisible(true);
        //  JOptionPane.showMessageDialog(null, "Logout Sucessfull");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Book abc = new Book();
        abc.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Booking book = new Booking();
 
        String[] print = bookingcheck.all;
        allemptyroom aa = new allemptyroom();
        aa.list1.clear();


        for (int i = 0; i < book.totalRooms; i++) {
            if (book.roomdata[i] == null) {

                String value = "Room " + (i + 1) + " is empty";
                aa.list1.add(value);
            }
        }



        aa.setVisible(true);


    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Book abc = new Book();
        abc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void sssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sssActionPerformed
        // TODO add your handling code here:
        Connection con = null;
        PreparedStatement pst = null;

        Statement st;
        Loginform ab = new Loginform();


        String temp = ab.getUsername();
        String url = "jdbc:mysql://localhost:3306/hoteldb";

        try {
            Connection con1 = DriverManager.getConnection(url, "root", "");
            Statement state1 = con1.createStatement();

            String sql = "UPDATE profile SET room=?,booking=? WHERE username=?";
            pst = con1.prepareStatement(sql);
            pst.setString(1, null);
            pst.setString(2, null);
            pst.setString(3, temp);

            pst.executeUpdate();

            JOptionPane.showMessageDialog(null, "Deleting all booking");
            this.dispose();
            ab.setVisible(true);
        } catch (Exception ex) {

        }

           Booking aa= new Booking();
           aa.deleteall();
    }//GEN-LAST:event_sssActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Book abc = new Book();
        abc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Book abc = new Book();
        abc.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JButton sss;
    private java.awt.TextArea textArea1;
    public static javax.swing.JLabel usernamefield;
    // End of variables declaration//GEN-END:variables
}
