
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.*;
import java.text.*; 
import java.util.*; 
import java.io.*;
import javax.swing.*;


import java.io.IOException; 
import java.util.logging.Level; 
import java.util.logging.Logger; 
import java.util.logging.*; /**
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Faiz
 */
public class Updateinfo extends javax.swing.JFrame { //gui for update account info
public String username;
String id,ic,phone,email;
String password,name;
 
Connection con=null;
     PreparedStatement pst=null;
   
     Statement st;
    /**
     * Creates new form Updateinfo
     */
    public Updateinfo() {
        initComponents();
    }
    public Updateinfo(String tempusername,String tempname,String temppassword,String tempid,String tempic,String tempphone,String email){
        initComponents();
        this.username=tempusername;
        this.password=temppassword;
        this.name=tempname;
        this.id=tempid;
        this.ic=tempic;
        this.phone=tempphone;
        this.email=email;
        usernamefield.setText(username);
        passwordfield.setText(password);
        namefield.setText(name);
        idfield.setText(id);
        icfield.setText(ic);
        phonefield.setText("0"+phone);
        emailfield.setText(email);
        
        
    }
    
    public void change(){
   
        //method to change your data at the database
        
        try{
       String sql="UPDATE profile SET Name=?,Password=?,Phonenumber=?,email=?,ICnumbe=? WHERE username =?";
        con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hoteldb","root","");
        pst = con.prepareStatement(sql);
        pst.setString(6, username);
        pst.setString(1, newname.getText());
        pst.setString(2, newpass.getText());
        pst.setString(3, newphone.getText());
        pst.setString(4, newemail.getText());
        pst.setString(5, newic.getText());
        
        pst.executeUpdate();
        
        JOptionPane.showMessageDialog(null,"Succefully update Data \n Relog again"); 
        
     
        
        
        
        
        
        
       }catch(Exception ex){
           
       }
        
        
        
    }
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        newic = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phonefield = new javax.swing.JLabel();
        newphone = new javax.swing.JTextField();
        icfield = new javax.swing.JLabel();
        idfield = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newname = new javax.swing.JTextField();
        newemail = new javax.swing.JTextField();
        passwordfield = new javax.swing.JLabel();
        namefield = new javax.swing.JLabel();
        emailfield = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        usernamefield = new javax.swing.JLabel();
        newpass = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        jButton3.setText("Change Info");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(260, 290, 90, 21);
        jPanel1.add(newic);
        newic.setBounds(280, 189, 150, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Phone number");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 240, 120, 22);

        phonefield.setText("jLabel9");
        jPanel1.add(phonefield);
        phonefield.setBounds(170, 230, 60, 30);
        jPanel1.add(newphone);
        newphone.setBounds(280, 229, 150, 30);

        icfield.setText("jLabel12");
        jPanel1.add(icfield);
        icfield.setBounds(170, 200, 50, 30);

        idfield.setText("jLabel13");
        jPanel1.add(idfield);
        idfield.setBounds(170, 280, 60, 13);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("IC number");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 200, 100, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("UserID");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(40, 280, 60, 22);
        jPanel1.add(newname);
        newname.setBounds(280, 109, 150, 30);
        jPanel1.add(newemail);
        newemail.setBounds(280, 149, 150, 30);

        passwordfield.setText("jLabel9");
        jPanel1.add(passwordfield);
        passwordfield.setBounds(170, 80, 50, 20);

        namefield.setText("jLabel10");
        jPanel1.add(namefield);
        namefield.setBounds(170, 120, 50, 20);

        emailfield.setText("jLabel11");
        jPanel1.add(emailfield);
        emailfield.setBounds(170, 160, 80, 20);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("New");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(290, 10, 50, 22);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Username");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(40, 40, 90, 22);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 80, 90, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(40, 160, 60, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Name");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(40, 120, 50, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Current");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(150, 10, 80, 22);

        usernamefield.setText("jLabel8");
        jPanel1.add(usernamefield);
        usernamefield.setBounds(170, 50, 40, 20);

        newpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newpassActionPerformed(evt);
            }
        });
        jPanel1.add(newpass);
        newpass.setBounds(280, 70, 150, 30);

        jButton1.setText("back to Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(380, 290, 100, 21);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/admin/okean-basseyn-otel-maldivy.jpg"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 590, 370);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        setSize(new java.awt.Dimension(589, 366));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void newpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newpassActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
     
       String url="jdbc:mysql://localhost:3306/hoteldb";
    //  JOptionPane.showMessageDialog(null, username);
  
    String name=newname.getText();
    String phone=newphone.getText();
    String email=newemail.getText();
    String ic1= newic.getText(); 
    String pass=newpass.getText();
    String user=usernamefield.getText();
   
       
      try{
          Connection con1= DriverManager.getConnection(url,"root","");
          Statement state1=con1.createStatement();
          
          
      
                 String sql = "UPDATE profile SET Password=?,Name=?,Phonenumber=?,email=? WHERE username=?";
                 pst=con1.prepareStatement(sql);
                 pst.setString(1, pass);
                 pst.setString(2, name);
                 pst.setString(3, phone);
                 pst.setString(4, email);
                 pst.setString(5, user);
        
          
         
          pst.executeUpdate();
          //pst.close();
          JOptionPane.showMessageDialog(null,"Succefully update Data \n Relog again");
          this.dispose();
      }catch(Exception ex){
          
      }
    //  JOptionPane.showMessageDialog(null, username);
      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Loginform login = new Loginform();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Updateinfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Updateinfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel emailfield;
    public static javax.swing.JLabel icfield;
    public static javax.swing.JLabel idfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel namefield;
    private javax.swing.JTextField newemail;
    private javax.swing.JTextField newic;
    private javax.swing.JTextField newname;
    private javax.swing.JTextField newpass;
    private javax.swing.JTextField newphone;
    public static javax.swing.JLabel passwordfield;
    private javax.swing.JLabel phonefield;
    public static javax.swing.JLabel usernamefield;
    // End of variables declaration//GEN-END:variables
}
